# This playbook contains example tasks to perform on a fresh Alpine Linux 
# installation. 
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved. Licensed under CC BY 3.0
#
# Usage: ansible-playbook setup.yml -f 10

---
- hosts: all
  user: root
  vars_files:
    - variables/application-versions.yml
    - variables/sensitive-variables.yml

  tasks:
#    - include: tasks/apk-repositories.yml
#    - include: tasks/motd.yml

# Server tasks
#    - include: tasks/lighttpd.yml
#    - include: tasks/dovecot.yml
#    - include: tasks/collectd.yml
#    - include: tasks/dnsmasq.yml
#    - include: tasks/mysql.yml

# Web application tasks
#    - include: tasks/linfo.yml
#    - include: tasks/bootstrap.yml
#    - include: tasks/phpsysinfo.yml
    - include: tasks/mutillidae.yml
#    - include: tasks/php-shell-detector.yml
#    - include: tasks/dvwa.yml
#    - include: tasks/phpmyadmin.yml
#

  handlers:
   - include: handlers/system.yml
