# This playbook contains operations to perform package management tasks on
# Alpine Linux hosts.
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
# 
---
- name: update the package list
  command: /sbin/apk update
  tags: update_cache

- name: update all packages
  command: /sbin/apk upgrade -U -a
  tags: update
  notify:
    - reboot system

- name: enable local cache
  command: /sbin/setup-apkcache $path
  tags: local_cache

- name: install a package
  command: /sbin/apk add $add_pkg
  tags: add_pkg

- name: remove a package
  command: /sbin/apk del $del_pkg
  tags: del_pkg

- name: clean package cache
  command: /sbin/apk cache clean
  tags: clean_chache
