# This playbook updates all Alpine Linux hosts.
#
# Copyright (c) 2013-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
# 
---
- name: update all packages
  raw: /sbin/apk upgrade -U -a

- name: reboot the system
  raw: /sbin/reboot -d 5
