# This files contains service handlers for Alpine Linux.
#
# Copyright (c) 2013-2017 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
# 
# Usage:
#  handlers:
#    - include: handlers/services.yml

---
# Control handlers for sshd 
- name: start sshd
  command: /etc/init.d/sshd start

- name: stop sshd
  command: /etc/init.d/sshd stop

- name: restart sshd
  command: /etc/init.d/sshd restart

# Control handlers for lighttpd 
- name: start lighttpd
  command: /etc/init.d/lighttpd start

- name: stop lighttpd
  command: /etc/init.d/lighttpd stop

- name: restart lighttpd
  command: /etc/init.d/lighttpd restart

# Control handlers for mysql 
- name: start mysql
  command: /etc/init.d/mysql start

- name: stop mysql
  command: /etc/init.d/mysql stop

- name: restart mysql
  command: /etc/init.d/mysql restart

# Control handlers for collectd 
- name: start collectd
  command: /etc/init.d/collectd start

- name: stop collectd
  command: /etc/init.d/collectd stop

- name: restart collectd
  command: /etc/init.d/collectd restart

# Control handlers for dnsmasq 
- name: start dnsmasq
  command: /etc/init.d/dnsmasq start

- name: stop dnsmasq
  command: /etc/init.d/dnsmasq stop

- name: restart dnsmasq
  command: /etc/init.d/dnsmasq restart
