# This playbook updates all Alpine Linux hosts and initialize a reboot.
#
# Copyright (c) 2013-2022 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under CC BY 3.0. All rights reserved.
#
---
- hosts: all
  user: root

  tasks:
  - name: update all packages
    command: /sbin/apk upgrade -U -a

  - name: reboot system
    command: /sbin/reboot -d 5
