# Example answer file for setup-alpine script
# If you don't want to use a certain option, then comment it out

# Use Swiss German layout
KEYMAPOPTS="de de_CH-latin1"

# Set hostname to alpine-test
HOSTNAMEOPTS="-n alpine-test"

# Contents of /etc/network/interfaces
INTERFACESOPTS="auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
	hostname alpine-test
"

# Search domain of example.com, Google public nameserver
DNSOPTS="-d example.com -n 8.8.8.8"

# Set timezone to UTC
TIMEZONEOPTS="-z UTC"

# set http/ftp proxy 
#PROXYOPTS="http://webproxy:8080"

# Add a random mirror
APKREPOSOPTS="-r"

# Install Openssh
SSHDOPTS="-c openssh"

# Use openntpd
NTPOPTS="-c openntpd"

# Use /dev/sda as a data disk
DISKOPTS="-m sys /dev/vda"

# Setup in /media/sdb1
#LBUOPTS="/media/sdb1"
#APKCACHEOPTS="/media/sdb1/cache"

